### ISSUE TITLE
Does this just look at the default install of msedge?

### ISSUE THREAD

**Issue by mudduck** [TBM13/BrowserSearch#10]
I have a personal profile logged in through outlook that i would like to be index (if possible). Its used inside both msedge dev and canary. Does this plugin index history of profile of those browsers or does it just look for the default edge install and the inherent profiles?

Great work, would love to use when confirmed. 

Thanks,
p.s. apologies if this was wrong forum for this request.

**Comment by TBM13** [comment]
The plugin only loads the history of a single browser (the one set as default on Windows). Your dev and canary installations would be considered two different browsers.

Additionally, beta/dev/canary versions of Chrome or Edge aren't supported right now (but supporting them should be as easy as adding the respective values [here](https://github.com/TBM13/BrowserSearch/blob/main/BrowserSearch/Main.cs#L102), I'll probably do it for the next release)

**Comment by TBM13** [comment]
If I understood correctly, you have the normal Edge set as default but you want to make the plugin load the history from either the dev or canary installations?

**Comment by mudduck** [comment]
ok, cool, appreciate your efforts.

respect, ✊
