### ISSUE TITLE
Possibly adding support for Arc browser

### ISSUE THREAD

**Issue by TheWeirdHomosapien** [TBM13/BrowserSearch#15]
A new chromium-based browser called "Arc" by the browser company just had a version launch for Windows. adding that to that list would be very helpful.

thank you.

**Comment by Harvelon365** [comment]
I agree this is a good idea!

**Comment by TBM13** [comment]
Where can I download this browser? Their website only says "Join Windows waitlist"

**Comment by Harvelon365** [comment]
It’s currently in beta so you just have to sign up for the waitlist then they’ll email you the download link when they want more testers.

**Comment by TBM13** [comment]
In that case I'll support it once it's released

**Comment by juangueo** [comment]
Hola Mateo, ARC está adquiriendo mucha popularidad. El método rápido para tener acceso a la version de Windows es recibiendo una invitación a la version Mac, recientemente han decidido que todo el que tenga la version mac, también puede accesar la version Windows.

Suena complicado, pero no lo es :) - Si me pasas tu email te envío un invite. JC

**Comment by TBM13** [comment]
> Hola Mateo, ARC está adquiriendo mucha popularidad. El método rápido para tener acceso a la version de Windows es recibiendo una invitación a la version Mac, recientemente han decidido que todo el que tenga la version mac, también puede accesar la version Windows.
> 
> Suena complicado, pero no lo es :) - Si me pasas tu email te envío un invite. JC

Suena bien, mi mail es `mateotrueba@gmail.com`

**Comment by artistro08** [comment]
Arc Just released yesterday and just saw that this was posted.

**Comment by TBM13** [comment]
> Arc Just released yesterday and just saw that this was posted.

I won't be adding support for it until it supports Windows 10. If anyone else is interested in supporting it, it shouldn't be difficult. Look at https://github.com/TBM13/BrowserSearch/commit/46509a70e2db06abcf6f985a518c4b6f089622e4 as reference

**Comment by TBM13** [comment]
Arc should now be supported on the latest release. Let me know if there is any issue
