### ISSUE TITLE
Browser 'Microsoft Edge' is not supported

### ISSUE THREAD

**Issue by deinfluence** [TBM13/BrowserSearch#16]
On PowerToys 0.80.1 start up, I keep seeing this message and I am not able to search my history. I am running v1.5.0

Any ideas why this is happening?

![image](https://github.com/TBM13/BrowserSearch/assets/27931868/1f7647ce-3d21-4729-9c32-8834fa4d8902)

**Comment by TBM13** [comment]
Strange. Can you send the latest log located at `%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs\0.80.1.0`?

**Comment by deinfluence** [comment]
[2024-04-26.txt](https://github.com/TBM13/BrowserSearch/files/15142621/2024-04-26.txt)

Attached is a log file. On reviewing it appears to occasionally show this error:
`[2024-04-26 22:31:15.3228] [ERROR] [C:\Cosas\Projects\C#\BrowserSearch\BrowserSearch\Main.cs::174]
Unsupported/unrecognized default browser ''`

**Comment by TBM13** [comment]
Seems to be the same issue than #17 . Will try to release a fix soon

**Comment by TBM13** [comment]
Should be fixed on the latest release. Let me know if it happens again.
