### ISSUE TITLE
Failed to initialize

### ISSUE THREAD

**Issue by electricsteve** [TBM13/BrowserSearch#22]
![image](https://github.com/TBM13/BrowserSearch/assets/96793824/b90e5a3f-c82f-495b-89ed-73131ac15693)

**Comment by electricsteve** [comment]
[2024-07-11.txt](https://github.com/user-attachments/files/16176427/2024-07-11.txt)

**Comment by TBM13** [comment]
Looks like you are using an older version of PowerToys while using the latest version of the plugin which was built for version 0.82

**Comment by electricsteve** [comment]
ok I'll see

**Comment by electricsteve** [comment]
Yep, worked
