### ISSUE TITLE
The plugin failed to initialize.

### ISSUE THREAD

**Issue by noobnooob197** [TBM13/BrowserSearch#23]
Hi, 

Thanks in advance for all your help.
I am running powertoys v0.82.0 on arm64.
I have installed browser search version 1.7.0.
I am getting this error 
![image](https://github.com/user-attachments/assets/c71ff67b-2f90-40cb-982c-5f6b9e85c92b)
My default browser is Microsoft Edge. I am a naive user and so do not understand much to be honest.

**I have also attacked the latest log:**
[2024-07-15.txt](https://github.com/user-attachments/files/16231449/2024-07-15.txt)

Thanks so much for all your help!

**Comment by TBM13** [comment]
I believe that's because the version in Releases is built for x64.
Just built it for ARM64, let me know if it works fine. If it does, I'll start releasing ARM64 builds from now on.
[BrowserSearch-arm64.zip](https://github.com/user-attachments/files/16239844/BrowserSearch-arm64.zip)

**Comment by noobnooob197** [comment]
Hi, Thanks so much for such a prompt reply!! It is working perfectly now. Thankyou again!!
