### ISSUE TITLE
Problem when using Arc

### ISSUE THREAD

**Issue by mnohrden** [TBM13/BrowserSearch#29]
I am trying to use BrowserSearch with Arc web browser, but it is just doing this:

https://github.com/user-attachments/assets/28697670-9000-4d98-b240-e365de1a97b7

Has anyone else encountered this issue?
I looked at the Main.cs file and I'm not sure why this _wouldn't_ be working, especially since it's chromium. Any help would be appreciated.

**Comment by TBM13** [comment]
So the issue is that the browser's history is not being loaded?
Also please send the latest Powertoys Run log (`%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Logs\`)

**Comment by mnohrden** [comment]
When I try to search, it will open arc and bring it to the foreground, but will not run a search with my query. I do have Arc configured as my default browser, but there must be something else...

Below is the log when I use BrowserSearch with Arc with input "arc hello":

[2024-09-20 15:32:52.1284] [WARN] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Helper.cs::155]
Trying to run OpenCommandInShell with an empty pattern. The default browser definition might have issues. Path: '$C:\Program Files\WindowsApps\TheBrowserCompany.Arc_1.20.0.50631_x64__ttt1ap7aakyb4\Arc.exe' ; Arguments: '$? arc hello' ; Working Directory: '$'

**Comment by TBM13** [comment]
I think you are confusing this plugin with PowerToys' Web Search plugin. BrowserSearch is for searching the browser's history, not the web.

**Comment by mnohrden** [comment]
That makes a lot more sense, I'll have to take a look at the Web Search Plugin
