### ISSUE TITLE
Failed to Initialize Brower Search

### ISSUE THREAD

**Issue by Ashwani-Chaurasiya** [TBM13/BrowserSearch#31]
Could you Please help to solve this issue, I am getting error Failed to Initialize Browser Search I am on Powertoys v0.85.1, I am using Mozilla Firefox and Windows 11 Pro

**Comment by TBM13** [comment]
Please send me the latest log. Should be at `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Logs\0.85.1.0`

**Comment by Ashwani-Chaurasiya** [comment]
@TBM13 Thank you for your quick response, it is fixed now, Actually this issue occurred when I installed firefox through Microsoft Store after downloading from Official website it worked perfectly.
