### ISSUE TITLE
Customizable search engines

### ISSUE THREAD

**Issue by LeVuMinhHuy** [TBM13/BrowserSearch#4]
Can we search from other engines, or sites, for example:

`Rickroll !y` --> will open youtube directly
`show me a cat meme !i` --> will open google image directly

...

Many thanks !

**Comment by TBM13** [comment]
The focus of this plugin is the browser. For now it only searches through the history and I may eventually expand it to also search through the bookmarks but other than that it's not supposed to interact with any website/search engine
