### ISSUE TITLE
Feature Request: Search Open (Running) Tabs

### ISSUE THREAD

**Issue by deryb** [TBM13/BrowserSearch#6]
I'd love this feature!  I'm visually impaired (brain damage), and too often I know I have a tab opened somewhere with information I need but forgot exactly where (which browser, which desktop, it might not be focused, etc).  

It'd be a game changer for me to extend the search to include ALL opened browser tabs eveywhere (in each browser, each profile). Similar to (itprobably should use that existing capability) the built-in tab search feature (via `Ctrl+Shift+A`).

I'm a retired developer and I'd like to maybe try my hand at this. I got java experience, but I could perhaps help "join the pipes" as I know my way around javascript and probably a good chunk of such plugin would need javascript to interrogate Chrome's API to feed Run's tool ?

A bit of help connecting the dots and hand holding of an old (rusty!) dev would be appreciated. Thanks for this already, I'll try and check it further later on. I just wanted to reach out to get something started.

**Comment by TBM13** [comment]
If it requires interacting directly with Chrome like you mentioned, I believe a new plugin should be created as I want to avoid making it harder to support other browsers.

Feel free to use this one as base so you don't have to setup the project from zero, but I doubt the code I wrote will be of any help

**Comment by deryb** [comment]
Thanks, yes that's what I thought. A Chrome plugin to call the existing tab
search feature and connect the pipes to PT's Run would be what I imagine. A
plugin per profile would be needed then, but that's a small hassle I think
is worth it, until there's a way to install extensions "chrome wide"
(global to all profiles).

I've not compiled C# projects before (maybe 10+ years ago lol), do you know
if it's possible with VSC (the free version I use for Javascript dev) ?
You're right I imagine there must be good basic project examples to start
with which would also do rather than hacking your code. Anyway, I'll try
and figure that all out when I get started, thanks for the contact!

Bruno

**Comment by TBM13** [comment]
Yes, Visual Studio Community is what I use. Good luck!
