### ISSUE TITLE
Feature Request: Support Firefox

### ISSUE THREAD

**Issue by AdrianoCahete** [TBM13/BrowserSearch#7]
Today is only Chrome and Edge because both use Chromium? It's possible to support Firefox?

**Comment by TBM13** [comment]
I'm not sure how Firefox stores the history but I guess it should be possible. Pull requests are welcome

**Comment by saurabh-mhaisekar** [comment]
@TBM13 hey if no one is working on this, i would like to take this on.

**Comment by TBM13** [comment]
> @TBM13 hey if no one is working on this, i would like to take this on.

Sure!

**Comment by ooTruffle** [comment]
To add to this

Firefox stores History and Bookmarks togeather in 
\AppData\Roaming\Mozilla\Firefox\Profiles\[profile name]\places.sqlite
